In [1]:
import findspark
findspark.init()
import pyspark
myConf=pyspark.SparkConf()
spark = pyspark.sql.SparkSession.builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

In [3]:
!pip install iplantuml

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for iplantuml: filename=IPlantUML-0.1.1-py2.py3-none-any.whl size=4896 sha256=545e3a0df693742c3402df87e384bf83f6ab2222e68d05f7c2173f8e00a7d12d
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\b9\d0\f5\e7d5a550ab924f9b6dfcf85359a1b7750e451d0d7611df0fb0
Successfully built iplantuml


In [4]:
import iplantuml

# Dense Vector

In [6]:
import numpy as np

In [7]:
dv = np.array([1.0, 2.1, 3])

In [8]:
from pyspark.mllib.linalg import Vectors

dv1mllib=Vectors.dense([1.0, 2.1, 3])

In [9]:
print ("Dense vector: {}\nType: {}".format(dv1mllib, type(dv1mllib)))

Dense vector: [1.0,2.1,3.0]
Type: <class 'pyspark.mllib.linalg.DenseVector'>


In [10]:
from pyspark.ml.linalg import Vectors

dv1ml=Vectors.dense([1.0, 2.1, 3])

In [11]:
print ("ml의 dense vector: {}".format(dv1ml))

ml의 dense vector: [1.0,2.1,3.0]


In [12]:
for e in dv1mllib:
    print (e, end = " ")

1.0 2.1 3.0 

In [13]:
dv1mllib.dot(dv1mllib)

14.41

In [14]:
np.dot(dv,dv)

14.41

In [15]:
dv1mllib*dv1mllib

DenseVector([1.0, 4.41, 9.0])

In [16]:
dv1mllib*2

DenseVector([2.0, 4.2, 6.0])

# Sparse Vectors

In [17]:
sv1 = Vectors.sparse(5,[0,1,4],[160.0,69.0,24.0])

In [18]:
type(sv1)

pyspark.ml.linalg.SparseVector

In [19]:
sv1.toArray()

array([160.,  69.,   0.,   0.,  24.])

# Matrix

In [20]:
from pyspark.mllib.linalg import Matrices

Matrices.dense(3, 2, [1,2,3,4,5,6])

DenseMatrix(3, 2, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0], False)

In [21]:
import numpy as np

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

In [22]:
import scipy.sparse as sps

mtx = sps.csc_matrix((data, (row, col)), shape=(3, 3))

In [23]:
print (mtx.todense())

[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [24]:
from pyspark.mllib.linalg import Matrices

dm = Matrices.dense(6,4,[1, 2, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 5, 6, 7, 0, 0, 0, 0, 0, 0, 8])

In [25]:

dm.toArray()

array([[1., 0., 0., 0.],
       [2., 3., 0., 0.],
       [0., 0., 5., 0.],
       [0., 4., 6., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 8.]])

In [26]:
dm.toSparse()

SparseMatrix(6, 4, [0, 2, 4, 7, 8], [0, 1, 1, 3, 2, 3, 4, 5], [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0], False)

In [27]:
sm = Matrices.sparse(3, 2, [0, 1, 3], [0, 2, 1], [9, 6, 8])

In [28]:
d=sm.toDense()

In [29]:
print (d)

DenseMatrix([[9., 0.],
             [0., 8.],
             [0., 6.]])


In [32]:
p = [[1.0,2.0,3.0],[1.1,2.1,3.1],[1.2,2.2,3.3]]

my=spark.sparkContext.parallelize(p)

In [33]:
from pyspark.mllib.linalg.distributed import RowMatrix

rm=RowMatrix(my)

In [34]:
rm.rows.collect()

[DenseVector([1.0, 2.0, 3.0]),
 DenseVector([1.1, 2.1, 3.1]),
 DenseVector([1.2, 2.2, 3.3])]

In [35]:
from pyspark.mllib.linalg.distributed import IndexedRow

irRdd = spark.sparkContext.parallelize([
    IndexedRow(1, [3, 1, 2]),
    IndexedRow(2, [1, 3, 2]),
    IndexedRow(3, [5, 4, 3]),
    IndexedRow(4, [6, 7, 4]),
    IndexedRow(5, [8, 9, 2]),
])

In [36]:
from pyspark.mllib.linalg.distributed import IndexedRowMatrix

irm = IndexedRowMatrix(irRdd)

In [37]:
print(irm.numRows())
print(irm.numCols())

6
3


In [38]:
from pyspark.mllib.regression import LabeledPoint

LabeledPoint(1.0, [1.0, 2.0, 3.0])

LabeledPoint(1.0, [1.0,2.0,3.0])

In [41]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors

LabeledPoint(1992, Vectors.sparse(10, {0: 3.0, 1:5.5, 2: 10.0}))

LabeledPoint(1992.0, (10,[0,1,2],[3.0,5.5,10.0]))

In [45]:
from pyspark.mllib.regression import LabeledPoint

LabeledPoint(1.0, dv1mllib)

LabeledPoint(1.0, [1.0,2.1,3.0])

In [46]:
from pyspark.mllib.regression import LabeledPoint
from pyspark.mllib.linalg import Vectors

LabeledPoint(1.0, Vectors.fromML(dv1ml))

LabeledPoint(1.0, [1.0,2.1,3.0])